bombora:
  outputs:
    dev:
      connect_timeout: 10
      dbname: ''
      host: ''
      keepalives_idle: 20
      password: ''
      port: ''
      schema: bombora_dwh
      threads: 10
      type: postgres
      user: ''
  target: dev
